# .github/workflows/ci.yml
name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: All checks passed
        run: echo "OK"
